management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongo
      password: ognom
      database: people
      port: 27017
      host: localhost        

logging:
  level:
    org.springframework.boot.web.embedded.netty: DEBUG
    reactor.ipc.netty.http: DEBUG
    org.springframework.http.server.reactive.ReactorHttpHandlerAdapter: DEBUG
    org.mongodb.driver: ERROR
    org.springframework.security: DEBUG