management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongo
      password: ognom
      database: people
      port: 27017
      host: localhost

logging:
  level:
    root: DEBUG
#    org.springframework.boot.web.embedded.netty: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#    reactor.ipc.netty.http: DEBUG
#    org.springframework.http.server.reactive.ReactorHttpHandlerAdapter: DEBUG
#    org.mongodb.driver: DEBUG
#    org.springframework.http.codec.json: DEBUG
#    org.springframework.security: WARN